### PR TITLE
fix: Unable to post test

### LINKED ISSUE #361: Unable to post test
Tested with build 20240216.4 in TEST env.
Reproduce steps:

1. start a hearing test
2. click 'Jeg hører lyden' for some times
3. pause the test several time and continue
4. finish the hearing test

Expected: Test result is sent successfully
Actually: Failed to send test result, error 400

image

### PR DESCRIPTION
**Pull request by dansvend**
The sound files was not always loaded before starting the test leading to the wrong sound duration being used in the start of the test. This led to a lot of `success` and `failure` actions to be dispatched at the wrong times.

Closes #361

### CODE REVIEW

**Review by tormodAase — APPROVED** [review]

File: hooks/useHearingTestIsFinished.ts [hunk 1]
```diff
@@ -14,7 +15,7 @@ export const useHearingTestIsFinished = () => {
   useEffect(() => {
     if (testIsFinished) {
       dispatch(postTest(test));
-      navigation.navigate("TestResultRoute");
+      navigation.dispatch(StackActions.replace("TestResultRoute"));
```
Comment (tormodAase) [inline hooks/useHearingTestIsFinished.ts:18]: Is there a reason for this change? If you need to use `replace` instead of `navigate`, wouldn't `navigation.replace` be sufficient?

If you need to use dispatch, I would suggest putting it inside of the saga instead?

Comment (dansvend) [reply hooks/useHearingTestIsFinished.ts]: I will open a new pull request for this. The code should now be similar to how it was when you approved it last time plus a resolved merge conflict with `main`.

**Review by tormodAase — APPROVED** [review]
