### PR TITLE
fix: Resolve issue with test not starting after restart

### LINKED ISSUE #218: Sounds not being played after restarting hearing test
How to reproduce: 
1. Start a new hearing test
2. Verify that you hear the sound samples
3. Pause the test
4. Click on "Start på ny"
5. The test will now restart, but the sounds will not be played

Skjermbilde 2023-06-05 kl  08 58 18

### PR DESCRIPTION
**Pull request by ofredstie**
- Reset user responses.
- Restart hearing test and start from the first test node.

Closes #218

### CODE REVIEW

File: screens/TestScreen.tsx [hunk 1]
```diff
@@ -215,7 +215,14 @@ class TestScreen extends Component {
     clearInterval(this.state.intervalId);
     this.props.actionStopTest();
     this.setState({ modalVisible: false });
+  }
+
+  restartTest() {
```
Comment (dansvend) [inline screens/TestScreen.tsx:220]: I see there are some code duplication in `abortTest` and `restartTest`. Would it be an idea to create another method called `stopTest` which can be reused in both `abortTest` and `restartTest`?

File: screens/TestScreen.tsx [hunk 2]
```diff
@@ -451,74 +458,41 @@ class TestScreen extends Component {
...
-                            onPress: () => {
-                              this.abortTest();
-                              this.props.navigation.navigate("TestRoute");
-                            },
-                            style: "destructive",
-                          },
-                        ]
+                        () => {
+                          this.restartTest();
+                          this.props.navigation.navigate("TestRoute");
```
Comment (dansvend) [inline screens/TestScreen.tsx:480]: I don't know if we need this line since we're already in the `TestRoute`.

File: screens/TestScreen.tsx [hunk 3]
```diff
@@ -537,6 +511,24 @@ class TestScreen extends Component {
   }
 }
 
+const setAlert = (
```
Comment (dansvend) [inline screens/TestScreen.tsx:514]: There's already a function which we use to display alerts in alerts.ts. Would be nice if you could change that and use that instead. We want to separate out reusable utility functions and components so that they're easier to find and maintain.

**Review by dansvend — CHANGES_REQUESTED** [review]

File: screens/TestScreen.tsx (hunk 3 above)
Comment (ofredstie) [reply screens/TestScreen.tsx:514]: I agree :+1:

File: screens/TestScreen.tsx (hunk 2 above)
Comment (ofredstie) [reply screens/TestScreen.tsx:480]: We didn't need it 😄

File: screens/TestScreen.tsx [hunk 4]
```diff
@@ -451,74 +461,41 @@ class TestScreen extends Component {
...
-                            onPress: () => {
-                              this.abortTest();
-                              this.props.navigation.navigate("TestRoute");
-                            },
-                            style: "destructive",
-                          },
-                        ]
+                        () => {
+                          this.restartTest();
+                          //this.props.navigation.navigate("TestRoute");
```
Comment (nesadrian) [inline screens/TestScreen.tsx:483]: I would delete this or add the reason why it's there in the code comment if it's important

File: screens/TestScreen.tsx [hunk 5]
```diff
@@ -209,13 +210,22 @@ class TestScreen extends Component {
...
-  abortTest() {
-    this.releaseSoundFiles();
-    Sound.setActive(false);
+  stopTest() {
     clearInterval(this.state.intervalId);
     this.props.actionStopTest();
     this.setState({ modalVisible: false });
+  }
+
+  abortTest() {
```
Comment (nesadrian) [inline screens/TestScreen.tsx:219]: The order of code execution order changes when the stopTest function call is at the top instead of the bottom in abortTest. If this is intended or insignificant then it's fine :)

**Review by nesadrian — CHANGES_REQUESTED** [review]

File: screens/TestScreen.tsx (hunk 4 above)
Comment (ofredstie) [reply screens/TestScreen.tsx:483]: My mistake, commented it out to test it, forgot to remove it. :+1:

**Review by nesadrian — APPROVED** [review]

File: utils/sound.ts [hunk 6]
```diff
@@ -9,3 +9,5 @@ export const createSoundFile = (filenameOrFile: any) => {
 
   return soundFile;
 };
+
+export const systemVolume: number = 0.5;
```
[the remark this answers is not in the document]
Comment (dansvend) [reply utils/sound.ts:13]: Also I think it's verbose to specify the type of this type of variable since the type is inferred by the TypeScript type inference system which takes responsibility away from us of writing the types.

File: utils/alerts.ts [hunk 7]
```diff
@@ -14,3 +14,21 @@ export const onClose = (onConfirm: (value?: string) => void) => {
...
+      text: "Nei",
+      onPress: () => {},
+      style: "cancel",
+    },
+    {
+      text: "Ja",
+      onPress: () => onConfirm(),
+      style: "destructive",
+    },
+  ]);
```
Comment (dansvend) [inline utils/alerts.ts:34]: The `setAlert` function and the `onClose` is basically the same. You should only keep one of them, and a fitting name would be what you have, `setAlert`.

File: screens/TestScreen.tsx [hunk 8]
```diff
@@ -32,7 +32,8 @@ import {
   selectTestIsFinished,
   selectTestIsRunning,
 } from "../store/test/reducer";
-import { createSoundFile } from "../utils/sound";
+import { setAlert } from "../utils/alerts";
```
Comment (dansvend) [inline screens/TestScreen.tsx:35]: Since you're not using `Alert` from `react-native` directly in this file anymore the import should be removed.

File: screens/TestScreen.tsx [hunk 9]
```diff
@@ -209,13 +210,22 @@ class TestScreen extends Component {
...
+
+  abortTest() {
+    this.releaseSoundFiles();
+    Sound.setActive(false);
+    this.stopTest();
+  }
+
+  restartTest() {
+    this.stopTest();
+    this.props.actionStartTest();
```
Comment (dansvend) [inline screens/TestScreen.tsx:228]: You might need to reset the `test`-reducer in redux to reset the user responses for example to start the new test without any user responses from the previous test run.

File: screens/TestScreen.tsx [hunk 10]
```diff
@@ -209,13 +210,22 @@ class TestScreen extends Component {
...
 
-  abortTest() {
-    this.releaseSoundFiles();
-    Sound.setActive(false);
+  stopTest() {
     clearInterval(this.state.intervalId);
     this.props.actionStopTest();
-    this.setState({ modalVisible: false });
     this.setState({ numberOfNodesPlayed: 0 });
+    this.setState({ modalVisible: false });
```
Comment (dansvend) [inline screens/TestScreen.tsx:217]: I see the order of these two have been changed. Probably doesn't matter but I'd keep it the way it was to not potentially introduce new bugs.

File: utils/alerts.ts [hunk 11]
```diff
@@ -14,3 +14,21 @@ export const onClose = (onConfirm: (value?: string) => void) => {
     },
   ]);
 };
+
+export const setAlert = (
+  heading: string,
```
Comment (dansvend) [inline utils/alerts.ts:19]: Could change this to `title` since that's the name `Alert.alert` uses to have consistency.

File: utils/alerts.ts [hunk 12]
```diff
@@ -14,3 +14,21 @@ export const onClose = (onConfirm: (value?: string) => void) => {
...
+  description: string,
```
Comment (dansvend) [inline utils/alerts.ts:20]: Could change this to `message` since that's the name `Alert.alert` uses to have consistency.

File: screens/TestScreen.tsx (hunk 2 above)
Comment (dansvend) [reply screens/TestScreen.tsx:483]: I see the navigation is still here. Is this needed? If so it could be added to the `restartTest` method.

**Review by dansvend — CHANGES_REQUESTED** [review]
Looks much better💪 I left some comments on possible improvements😊

File: utils/alerts.ts (hunk 11 above)
Comment (ofredstie) [reply utils/alerts.ts:19]: Could not agree more.. :D

File: utils/alerts.ts (hunk 12 above)
Comment (ofredstie) [reply utils/alerts.ts:20]: I agree

File: screens/TestScreen.tsx (hunk 9 above)
Comment (ofredstie) [reply screens/TestScreen.tsx:229]: Tested with React Native Debugger and can verify that userResponses is reset after test is restarted

File: app.json [hunk 13]
```diff
@@ -15,11 +15,11 @@
...
       "fallbackToCacheTimeout": 0
     },
-    "assetBundlePatterns": [
-      "**/*"
-    ],
+    "assetBundlePatterns": ["**/*"],
+    "jsEngine": "hermes",
     "ios": {
       "supportsTablet": true,
+      "jsEngine": "jsc",
```
Comment (dansvend) [inline app.json:22]: Does this still work when running Expo SDK 49?

File: screens/SoundCheckScreen.tsx [hunk 14]
```diff
@@ -72,7 +73,8 @@ const SoundCheckScreen = (props: any) => {
     Sound.setMode("Measurement");
     Sound.setActive(true);
 
-    SystemSetting.setVolume(0.5, { showUI: false });
+    // Load the sound file 'testBell.wav' from the app bundle
```
Comment (dansvend) [inline screens/SoundCheckScreen.tsx:76]: This comment can be removed.

File: utils/alerts.ts [hunk 15]
```diff
@@ -1,16 +1,19 @@
 import { Alert } from "react-native";
 
-export const onClose = (onConfirm: (value?: string) => void) => {
-  Alert.alert("Avslutte?", "Da må du begynne på nytt neste gang", [
+export const setAlert = (
```
Comment (dansvend) [inline utils/alerts.ts:3]: After thinking about this `confirmationDialog` is a more suitable name since "Ja" and "Nei" is hardcoded.

File: utils/alerts.ts [hunk 16]
```diff
@@ -1,16 +1,19 @@
...
+  title: string,
+  message: string,
+  onConfirm: CallableFunction
```
Comment (dansvend) [inline utils/alerts.ts:6]: This should have a type similar to `onPress` on the `AlertButton` type.

File: utils/alerts.ts [hunk 17]
```diff
@@ -1,16 +1,19 @@
...
+  Alert.alert(title, message, [
     {
       text: "Nei",
       onPress: () => {},
       style: "cancel",
     },
     {
       text: "Ja",
-      onPress: onConfirm,
+      onPress: () => onConfirm(),
```
Comment (dansvend) [inline utils/alerts.ts:16]: This can be changed to how it was.

File: screens/SoundCheckScreen.tsx [hunk 18]
```diff
@@ -125,8 +127,8 @@ const SoundCheckScreen = (props: any) => {
   function playAudioTest(ear: "left" | "right") {
     // Setting volume each time just to make sure the volume is not changed between plays
     // also, if headset was plugged in after componentDidMount() was called, we need to call this again
-    SystemSetting.setVolume(0.5, { showUI: false }); //Todo: Disabling this until we know how the calibration step should be done..
-    sound.setVolume(0.5);
+    SystemSetting.setVolume(SYSTEM_VOLUME, { showUI: false }); //Todo: Disabling this until we know how the calibration step should be done..
```
Comment (dansvend) [inline screens/SoundCheckScreen.tsx:130]: The `Todo` comment can be removed.

File: screens/TestScreen.tsx [hunk 19]
```diff
@@ -15,6 +15,7 @@ import { MenuItem } from "../components/common/atoms/MenuItem";
 import ProgressBar from "../components/common/atoms/ProgressBar";
 import Typography from "../components/common/atoms/Typography";
 import { TestCard } from "../components/common/molecules/TestCard";
+import { SYSTEM_VOLUME } from "../constants/sounds";
```
Comment (dansvend) [inline screens/TestScreen.tsx:18]: Please remove import of `Alert` on line 5 since it's no longer in use.

**Review by dansvend — CHANGES_REQUESTED** [review]

File: screens/TestScreen.tsx (hunk 2 above)
Comment (ofredstie) [reply screens/TestScreen.tsx:484]: Navigation need to be there

**Review by dansvend — APPROVED** [review]

**Review by nesadrian — APPROVED** [review]
