### PR TITLE
fix: Display dialog when pressing no on subdialog

### LINKED ISSUE #356: Stuck on spinner after canceling stopping test
How to reproduce:
1. Press the pause button during a hearing test
2. Press on "Avslutte testen" or "Start på ny"
3. Press on "Nei"

This should continue the test.

### PR DESCRIPTION
**Pull request by dansvend**
Previously when pressing no on a subdialog of the pause modal during a hearing test the screen would be stuck displaying a spinner. This commit fixes that issue.

Closes #356

### CODE REVIEW

File: hooks/useHearingTest.ts [hunk 1]
```diff
@@ -169,20 +186,31 @@ export const useHearingTest = () => {
     navigation.navigate("TestRoute");
   };
 
+  console.log({
+    isFetching,
+    isSoundFilesLoaded,
+    pauseAfterNode,
+    dialog,
+  });
+
```
Comment (nesadrian) [inline hooks/useHearingTest.ts:195]: Remove console log

File: hooks/useHearingTest.ts [hunk 2]
```diff
@@ -59,19 +67,28 @@ export const useHearingTest = () => {
...
-  }, [pauseAfterNode, isDialogOpen, node]);
+  }, [pauseAfterNode, dialog, node]);
 
   useEffect(() => {
-    if (!testIsRunning || pauseAfterNode || isDialogOpen) {
+    if (
+      !testIsRunning ||
+      pauseAfterNode ||
+      dialog === DIALOG.OPEN ||
+      dialog === DIALOG.SUBDIALOG
```
Comment (nesadrian) [inline hooks/useHearingTest.ts:85]: If this is replaced with "dialog !== DIALOG.HIDDEN" it's less code and there won't be as much refactoring to do if other states are added.

File: hooks/useHearingTest.ts [hunk 3]
```diff
@@ -169,20 +186,31 @@ export const useHearingTest = () => {
...
+    dialog,
+  });
+
   const isLoading =
-    isFetching || !isSoundFilesLoaded || pauseAfterNode || isDialogOpen;
+    isFetching ||
+    !isSoundFilesLoaded ||
+    pauseAfterNode ||
+    dialog === DIALOG.OPEN ||
+    dialog === DIALOG.SUBDIALOG;
```
Comment (nesadrian) [inline hooks/useHearingTest.ts:201]: If this is replaced with "dialog !== DIALOG.HIDDEN" it's less code and there won't be as much refactoring to do if other states are added.

File: screens/TestScreen/TestScreenComponent.tsx [hunk 4]
```diff
@@ -95,53 +95,56 @@ export const TestScreenComponent = () => {
           <BottomButton />
         </View>
       </SafeAreaView>
-      <Dialog isOpen={isDialogOpen}>
+      <Dialog isOpen={dialog === DIALOG.OPEN || dialog === DIALOG.SUBDIALOG}>
```
Comment (nesadrian) [inline screens/TestScreen/TestScreenComponent.tsx:98]: If this is replaced with "dialog !== DIALOG.HIDDEN" it's less code and there won't be as much refactoring to do if other states are added.

File: hooks/useHearingTest.ts (hunk 1 above)
Comment (dansvend) [reply hooks/useHearingTest.ts:195]: Done

File: hooks/useHearingTest.ts (hunk 2 above)
Comment (dansvend) [reply hooks/useHearingTest.ts:85]: Then you're making assumptions that all new states will have the same functionality as `open` and `subdialog` which I think is more dangerous and will potentially break more than by explicitly adding states to a condition.

Comment (dansvend) [reply hooks/useHearingTest.ts]: I've refactored this.

File: hooks/useHearingTest.ts (hunk 3 above)
Comment (dansvend) [reply hooks/useHearingTest.ts]: I've refactored this.

File: screens/TestScreen/TestScreenComponent.tsx (hunk 4 above)
Comment (dansvend) [reply screens/TestScreen/TestScreenComponent.tsx]: I've refactored this.

**Review by nesadrian — APPROVED** [review]
