### PR TITLE
fix: Unable to start a second test during the same session

### LINKED ISSUE #367: Unable to start a second test during the same session
A user is unable to start a second test during the same session. This is due to the test state not being cleared after finishing a test.

### PR DESCRIPTION
**Pull request by dansvend**
A user was unable to start a second test during the same session since the test state reducer was not reset.

Closes #367

### CODE REVIEW

**Review by tormodAase — APPROVED** [review]

**Review by tormodAase — DISMISSED** [review]

**Review by tormodAase — APPROVED** [review]

File: screens/TestScreen/TestScreenComponent.tsx [hunk 1]
```diff
@@ -29,6 +29,12 @@ export const TestScreenComponent = () => {
   } = useHearingTest();
   const navigation = useHearingNavigation();
 
+  const getSubheading = () => {
+    if (isLoading) return "";
+    if (testIsRunning) return "Trykk på sirkelen under når du hører en lyd";
+    return "Trykk på sirkelen under når du er klar for å starte hørselstesten.";
+  };
```
Comment (tormodAase) [inline screens/TestScreen/TestScreenComponent.tsx:36]: Since we've had so much focus on testing today, it might be smart to look at how we create our functions. If `getSubheading` is refactored into a pure function, it might be easier to implement tests for it

Comment (dansvend) [reply screens/TestScreen/TestScreenComponent.tsx]: Good point! Done in [47c14ee](https://github.com/equinor/hearing-test/pull/368/commits/47c14ee589fefc8cefee79fa38d3ef62c94bad99) and [5e47b5e](https://github.com/equinor/hearing-test/pull/368/commits/5e47b5eb96fdcf57f3dfc3fef6862b2b0b9cb7c1) 🧪

File: utils/hearing-test/getSubheading.test.ts [hunk 2]
```diff
@@ -0,0 +1,23 @@
...
+  test(`should return "${SUBHEADINGS.TEST_HAS_LOADED}" when both isLoading and isTestRunning are false`, () => {
+    const subheading = getSubheading(false, false);
+    expect(subheading).toBe(SUBHEADINGS.TEST_HAS_LOADED);
+  });
+
+  test(`should return "${SUBHEADINGS.LOADING}" when both isLoading and isTestRunning are true`, () => {
+    const subheading = getSubheading(true, true);
+    expect(subheading).toBe(SUBHEADINGS.LOADING);
+  });
+});
```
Comment (tormodAase) [inline utils/hearing-test/getSubheading.test.ts:23]: To make sure people do not accidentally change the subheadings, I would add another test for the subheadings:

```ts
  test("Subheadings should have exact values", () => {
    expect(SUBHEADINGS.LOADING).toBe("");
    expect(SUBHEADINGS.TEST_IS_RUNNING).toBe("Trykk på sirkelen under når du hører en lyd")
    expect(SUBHEADINGS.TEST_HAS_LOADED).toBe("Trykk på sirkelen under når du er klar for å starte hørselstesten.")
  })
```

Comment (dansvend) [reply utils/hearing-test/getSubheading.test.ts]: Good catch 💪  Done in [10626df](https://github.com/equinor/hearing-test/pull/368/commits/10626df1cdf81e2adfe08a1924deda3bb73eb621) 🧪

**Review by tormodAase — APPROVED** [review]
